version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    cooldown:
      default-days: 7
    labels:
      - "internal"
      - "dependencies"
      - "github_actions"
    groups:
      github-actions:
        patterns:
          - "*"
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    cooldown:
      default-days: 7
    labels:
      - "internal"
      - "dependencies"
      - "python:pip"
    groups:
      python-packages:
        dependency-type: "development"
        patterns:
          - "*"
