version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Python dependencies, covers root dependencies for development and also ./docker-images
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
