name: Deploy
on:
  push:
    branches:
      - master
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"
permissions: {}
jobs:
  deploy:
    permissions:
      contents: read
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.12"
          - name: python3.12
            python_version: "3.12"
          - name: python3.11
            python_version: "3.11"
          - name: python3.10
            python_version: "3.10"
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Set Dockerfile name
        if: matrix.image.name != 'latest'
        run: echo "DOCKERFILE_NAME=${{ matrix.image.name }}" >> $GITHUB_ENV
      - name: Set Dockerfile name latest
        if: matrix.image.name == 'latest'
        run: echo "DOCKERFILE_NAME=python${{ matrix.image.python_version }}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get date for tags
        run: echo "DATE_TAG=$(date -I)" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: "tiangolo/uwsgi-nginx-flask:${{ matrix.image.name }}\ntiangolo/uwsgi-nginx-flask:${{ matrix.image.name }}-${{ env.DATE_TAG }} \n"
          context: ./docker-images/
          file: ./docker-images/${{ env.DOCKERFILE_NAME }}.dockerfile
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: tiangolo/uwsgi-nginx-flask
