name: Deploy
on:
  push:
    branches:
      - master
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"
permissions: {}
jobs:
  deploy:
    permissions:
      contents: read
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.12"
          - name: python3.12
            python_version: "3.12"
          - name: python3.11
            python_version: "3.11"
          - name: python3.10
            python_version: "3.10"
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set Dockerfile name
        if: matrix.image.name != 'latest'
        run: echo "DOCKERFILE_NAME=${{ matrix.image.name }}" >> $GITHUB_ENV
      - name: Set Dockerfile name latest
        if: matrix.image.name == 'latest'
        run: echo "DOCKERFILE_NAME=python${{ matrix.image.python_version }}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Login to DockerHub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get date for tags
        run: echo "DATE_TAG=$(date -I)" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            tiangolo/uwsgi-nginx-flask:${{ matrix.image.name }}
            tiangolo/uwsgi-nginx-flask:${{ matrix.image.name }}-${{ env.DATE_TAG }} 
          context: ./docker-images/
          file: ./docker-images/${{ env.DOCKERFILE_NAME }}.dockerfile
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: tiangolo/uwsgi-nginx-flask
