name: Issue Manager

on:
  schedule:
    - cron: "15 9 * * *"
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - labeled
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@75d60679db1ea348f6f6ea1d0e20de80a7c04645 # 0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
