name: Issue Manager

on:
  schedule:
    - cron: "15 9 * * *"
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - labeled
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@dc846170c36eb62fb434b3d943b36399fe240fb5 # 0.8.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
