name: Test
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"
permissions: {}
jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.12"
          - name: python3.12
            python_version: "3.12"
          - name: python3.11
            python_version: "3.11"
          - name: python3.10
            python_version: "3.10"
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set Dockerfile name
        if: matrix.image.name != 'latest'
        run: echo "DOCKERFILE_NAME=${{ matrix.image.name }}" >> $GITHUB_ENV
      - name: Set Dockerfile name latest
        if: matrix.image.name == 'latest'
        run: echo "DOCKERFILE_NAME=python${{ matrix.image.python_version }}" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          push: false
          tags: tiangolo/uwsgi-nginx-flask:${{ matrix.image.name }}
          context: ./docker-images/
          file: ./docker-images/${{ env.DOCKERFILE_NAME }}.dockerfile
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: python -m pip install docker pytest
      - name: Test Image
        run: pytest tests
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
  check:
    if: always()
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
